ter 20 ago 2024 10:36:23 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/usr/bin/biglinux-verify-md5sum b/usr/bin/biglinux-verify-md5sum
--- a/usr/bin/biglinux-verify-md5sum
+++ b/usr/bin/biglinux-verify-md5sum
@@ -49,38 +49,51 @@ function biglinux-verify-md5sum_main() {
 	local Verification_canceled=$"Verification canceled."
 	local The_files_are_intact=$"The files are intact."
 	local md5sum_file_fail='/tmp/md5sum_big_fail'
+	local squashfiles=('desktopfs' 'livefs' 'mhwdfs' 'rootfs')
+	local cfile
 	local verify=2
 	local content
+	local count=0
 
 	[[ -e "$md5sum_file_fail" ]] && rm -f "$md5sum_file_fail"
 	if cd /run/miso/bootmnt/manjaro/x86_64/ >/dev/null 2>&- ; then
 		(
-			#			echo "10"
-			#			echo "# $Message2 \n\n $Message desktopfs.sfs"
-			if ! md5sum --status -c desktopfs.md5; then
-				echo 1 >"$md5sum_file_fail"
-			fi
-			printf "%s\n" "25"
-			printf "%s\n" "# $Message2 \n\n $Message desktopfs.sfs"
-
-			if ! md5sum --status -c livefs.md5; then
-				echo 1 >"$md5sum_file_fail"
-			fi
-			printf "%s\n" "50"
-			printf "%s\n" "# $Message2 \n\n $Message livefs.sfs"
-
-			if ! md5sum --status -c mhwdfs.md5; then
-				echo 1 >"$md5sum_file_fail"
-			fi
-			printf "%s\n" "75"
-			printf "%s\n" "# $Message2 \n\n $Message mhwdfs.sfs"
-
-			if ! md5sum --status -c rootfs.md5; then
-				echo 1 >"$md5sum_file_fail"
-			fi
-			printf "%s\n" "100"
-			printf "%s\n" "# $Message2 \n\n $Message rootfs.sfs"
+			for cfile in "${squashfiles[@]}"; do
+				if ! md5sum --status -c ${cfile}.md5; then
+					echo 1 >"$md5sum_file_fail"
+				fi
+				count+=25
+				printf "%s\n" "$count"
+				printf "%s\n" "# $Message2 \n\n $Message ${cfile}.sfs"
+			done
 			sleep 1
+#
+#			#			echo "10"
+#			#			echo "# $Message2 \n\n $Message desktopfs.sfs"
+#			if ! md5sum --status -c desktopfs.md5; then
+#				echo 1 >"$md5sum_file_fail"
+#			fi
+#			printf "%s\n" "25"
+#			printf "%s\n" "# $Message2 \n\n $Message desktopfs.sfs"
+#
+#			if ! md5sum --status -c livefs.md5; then
+#				echo 1 >"$md5sum_file_fail"
+#			fi
+#			printf "%s\n" "50"
+#			printf "%s\n" "# $Message2 \n\n $Message livefs.sfs"
+#
+#			if ! md5sum --status -c mhwdfs.md5; then
+#				echo 1 >"$md5sum_file_fail"
+#			fi
+#			printf "%s\n" "75"
+#			printf "%s\n" "# $Message2 \n\n $Message mhwdfs.sfs"
+#
+#			if ! md5sum --status -c rootfs.md5; then
+#				echo 1 >"$md5sum_file_fail"
+#			fi
+#			printf "%s\n" "100"
+#			printf "%s\n" "# $Message2 \n\n $Message rootfs.sfs"
+#			sleep 1
 
 		) |
 			zenity \
