dom 18 ago 2024 23:58:39 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -1,4 +1,43 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#shellcheck disable=SC2155,SC2034
+#shellcheck source=/dev/null
+
+#  /usr/bin/calamares-biglinux
+#  Description: Big Store installing programs for BigLinux
+#
+#  Created: 2020/01/11
+#  Altered: 2024/08/18
+#
+#  Copyright (c) 2023-2024, Vilmar Catafesta <vcatafesta@gmail.com>
+#  All rights reserved.
+#
+#  Redistribution and use in source and binary forms, with or without
+#  modification, are permitted provided that the following conditions
+#  are met:
+#  1. Redistributions of source code must retain the above copyright
+#     notice, this list of conditions and the following disclaimer.
+#  2. Redistributions in binary form must reproduce the above copyright
+#     notice, this list of conditions and the following disclaimer in the
+#     documentation and/or other materials provided with the distribution.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
+#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
+#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
+#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
+#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
+#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
+#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+APP="${0##*/}"
+_VERSION_="1.0.0-20240818"
+#
+LIBRARY=${LIBRARY:-'/usr/share/bigbashview/bcc/shell'}
+[[ -f "${LIBRARY}/bcclib.sh" ]] && source "${LIBRARY}/bcclib.sh"
+[[ -f "${LIBRARY}/tinilib.sh" ]] && source "${LIBRARY}/tinilib.sh"
+[[ -f "${LIBRARY}/bstrlib.sh" ]] && source "${LIBRARY}/bstrlib.sh"
 
 #Translation
 export TEXTDOMAINDIR="/usr/share/locale"
@@ -6,64 +45,63 @@ export TEXTDOMAIN=calamares-biglinux
 
 # md5sum
 if [ "$(ps -e | grep biglinux-verify)" != "" ]; then
-    windowID="$(xprop -root '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)"
-    sleep 600 | zenity --attach="$windowID" --width=300 --progress --title=$"Please wait..." --pulsate --no-cancel --auto-close --text $"Checking the integrity of the download and storage device..." &
+	windowID="$(xprop -root '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)"
+	sleep 600 | zenity --attach="$windowID" --width=300 --progress --title=$"Please wait..." --pulsate --no-cancel --auto-close --text $"Checking the integrity of the download and storage device..." &
 fi
 
 while [ "$(ps -e | grep biglinux-verify)" != "" ]; do
-    sleep 1
+	sleep 1
 done
 
 killall zenity
 
 if [ ! -f "/tmp/checksum_biglinux_ok.html" ]; then
-    /usr/bin/biglinux-verify-md5sum
-    if [ -f "/tmp/md5sum_big_fail" ]; then
-        exit 1
-    fi
+	/usr/bin/biglinux-verify-md5sum
+	if [ -f "/tmp/md5sum_big_fail" ]; then
+		exit 1
+	fi
 fi
 
 # if the ISO was generated more than 30 days ago, issue ALERT
-if [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $(cat /etc/big-release | grep UNIX_TIMESTAMP= | cut -d "=" -f2) + 30 ))" ]; then
-    yad --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
-    --align=center \
-    --field=$"<b>Do you want to proceed with the installation of this old version anyway?</b>
+if [ "$(echo $(($(date +%s) / 86400)))" -gt "$(($(cat /etc/big-release | grep UNIX_TIMESTAMP= | cut -d "=" -f2) + 30))" ]; then
+	yad --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
+		--align=center \
+		--field=$"<b>Do you want to proceed with the installation of this old version anyway?</b>
     :LBL" \
-    --text $"BigLinux is a system with weekly updates and this version was released more than a month ago.\nWe recommend downloading a more recent version.
+		--text $"BigLinux is a system with weekly updates and this version was released more than a month ago.\nWe recommend downloading a more recent version.
     " \
-    --button=$"Continue":0 \
-    --button=$"Close":1 \
-    --center --on-top --borders=20 --title=$"Outdated Version" \
-    --window-icon=emblem-warning
+		--button=$"Continue":0 \
+		--button=$"Close":1 \
+		--center \
+		--on-top \
+		--borders=20 \
+		--title=$"Outdated Version" \
+		--window-icon=emblem-warning
 
-    if [ "$?" = "1" ]; then
-        exit 1
-    fi
+	if [ "$?" = "1" ]; then
+		exit 1
+	fi
 fi
 
 # disable swap on disk
-for diskswap in $(blkid | grep 'TYPE="swap"' | grep -v zram | cut -f1 -d:)
-do
-    swapoff $diskswap
+for diskswap in $(blkid | grep 'TYPE="swap"' | grep -v zram | cut -f1 -d:); do
+	swapoff $diskswap
 done
 
-if [ "${LANG:0:2}" = "pt" ]
-then
-    sed -i 's|pt/|pt/|g' /usr/share/calamares/branding/biglinux/show.qml
-elif [ "${LANG:0:2}" = "es" ]
-then
-    sed -i 's|pt/|es/|g' /usr/share/calamares/branding/biglinux/show.qml
+if [ "${LANG:0:2}" = "pt" ]; then
+	sed -i 's|pt/|pt/|g' /usr/share/calamares/branding/biglinux/show.qml
+elif [ "${LANG:0:2}" = "es" ]; then
+	sed -i 's|pt/|es/|g' /usr/share/calamares/branding/biglinux/show.qml
 
 else
-    sed -i 's|pt/|en/|g' /usr/share/calamares/branding/biglinux/show.qml
+	sed -i 's|pt/|en/|g' /usr/share/calamares/branding/biglinux/show.qml
 fi
-
 
 if [ ! -f "/etc/calamares/biglinux" ]; then
 
-# Simplify welcome
+	# Simplify welcome
 
-echo '---
+	echo '---
 showSupportUrl:         false
 showKnownIssuesUrl:     false
 showReleaseNotesUrl:    false
@@ -87,36 +125,35 @@ geoip:
     style:    "none"
     url:      "https://geoip.kde.org/v1/ubiquity"
     selector: "CountryCode"
-      ' > /etc/calamares/modules/welcome.conf
+      ' >/etc/calamares/modules/welcome.conf
 
-# Force btrfs compression using zstd
-sed -i '/filesystem: btrfs/!b; :a; n; /^\s\{6\}options:/ s/defaults.*/defaults, noatime, compress-force=zstd:9 ]\n      ssdOptions: [ discard=async ]\n      hddOptions: [ autodefrag ]/; ta' /usr/share/calamares/modules/mount.conf
+	# Force btrfs compression using zstd
+	sed -i '/filesystem: btrfs/!b; :a; n; /^\s\{6\}options:/ s/defaults.*/defaults, noatime, compress-force=zstd:9 ]\n      ssdOptions: [ discard=async ]\n      hddOptions: [ autodefrag ]/; ta' /usr/share/calamares/modules/mount.conf
 
-# btrfs: defaults,noatime,autodefrag,compress=zstd
-#sed -i 's|btrfs: defaults|btrfs: defaults,noatime,compress=zstd|g' /usr/share/calamares/modules/fstab.conf
-#sed -i 's|btrfs: discard=async,ssd|#btrfs: discard=async,ssd|g' /usr/share/calamares/modules/fstab.conf
-#sed -i 's|ssdExtraMountOptions:|#ssdExtraMountOptions:|g' /usr/share/calamares/modules/fstab.conf
+	# btrfs: defaults,noatime,autodefrag,compress=zstd
+	#sed -i 's|btrfs: defaults|btrfs: defaults,noatime,compress=zstd|g' /usr/share/calamares/modules/fstab.conf
+	#sed -i 's|btrfs: discard=async,ssd|#btrfs: discard=async,ssd|g' /usr/share/calamares/modules/fstab.conf
+	#sed -i 's|ssdExtraMountOptions:|#ssdExtraMountOptions:|g' /usr/share/calamares/modules/fstab.conf
 
-# Use btrfs for default
-sed -i 's|defaultFileSystemType.*"ext4"|defaultFileSystemType:  "btrfs"|g' /usr/share/calamares/modules/partition.conf
+	# Use btrfs for default
+	sed -i 's|defaultFileSystemType.*"ext4"|defaultFileSystemType:  "btrfs"|g' /usr/share/calamares/modules/partition.conf
 
-# Change initcpio to systemd
-#sed -i 's|"base", "udev"|"systemd"|g' /usr/lib/calamares/modules/initcpiocfg/main.py
+	# Change initcpio to systemd
+	#sed -i 's|"base", "udev"|"systemd"|g' /usr/lib/calamares/modules/initcpiocfg/main.py
 
-# Clean initcpio
-#sed -i 's|, "keyboard", "keymap", "consolefont"||g' /usr/lib/calamares/modules/initcpiocfg/main.py
+	# Clean initcpio
+	#sed -i 's|, "keyboard", "keymap", "consolefont"||g' /usr/lib/calamares/modules/initcpiocfg/main.py
 
-# Change initcpio plymouth to sd version
-sed -i 's|"plymouth"|"kms plymouth"|g' /usr/lib/calamares/modules/initcpiocfg/main.py
+	# Change initcpio plymouth to sd version
+	sed -i 's|"plymouth"|"kms plymouth"|g' /usr/lib/calamares/modules/initcpiocfg/main.py
 
+	# not disable pacman-init
+	# sed -i '/^disable:/,$d' /usr/share/calamares/modules/services.conf
 
-# not disable pacman-init
-# sed -i '/^disable:/,$d' /usr/share/calamares/modules/services.conf
+	# failsafe if services not generated in boot
+	if [ "$(cat /etc/calamares/modules/services.conf | wc -l)" -lt "15" ]; then
 
-# failsafe if services not generated in boot
-if [ "$(cat /etc/calamares/modules/services.conf | wc -l)" -lt "15" ]; then
-
-echo 'services:
+		echo 'services:
     - name: bluetooth
       mandatory: false
 
@@ -171,14 +208,13 @@ targets:
 
 disable:
     - name: pacman-init
-      mandatory: false' > /etc/calamares/modules/services.conf
+      mandatory: false' >/etc/calamares/modules/services.conf
 
-fi
+	fi
 
-sed -i 's|timers:||g' /etc/calamares/modules/services.conf
+	sed -i 's|timers:||g' /etc/calamares/modules/services.conf
 
-
-echo "
+	echo "
 ---
 defaultGroups:
     - cdrom
@@ -209,20 +245,18 @@ availableShells: /bin/bash, /bin/zsh
 avatarFilePath:  ~/.face
 userShell:       /bin/bash
 passwordRequirements:
-    nonempty: true" > /etc/calamares/modules/users.conf
+    nonempty: true" >/etc/calamares/modules/users.conf
 
-
-echo '---
+	echo '---
 keyrings:
     - archlinux
     - manjaro
-    - biglinux' > /etc/calamares/modules/postcfg.conf
-    
+    - biglinux' >/etc/calamares/modules/postcfg.conf
 
-#sed -i 's|initialSwapChoice: none|initialSwapChoice: small|g' /etc/calamares/modules/partition.conf
+	#sed -i 's|initialSwapChoice: none|initialSwapChoice: small|g' /etc/calamares/modules/partition.conf
 
-# General configuration
-echo '---
+	# General configuration
+	echo '---
 modules-search: [ local ]
 
 sequence:
@@ -269,10 +303,9 @@ dont-chroot: false
 oem-setup: false
 disable-cancel: false
 disable-cancel-during-exec: false
-quit-at-end: false' > /etc/calamares/settings.conf
+quit-at-end: false' >/etc/calamares/settings.conf
 
-
-touch /etc/calamares/biglinux
+	touch /etc/calamares/biglinux
 
 fi
 
@@ -285,85 +318,78 @@ rm -f /tmp/efi-partitions
 mkdir -p /boot/efi
 
 DEVICE_LIVE_BOOT_TMP="$(readlink -f "$(df -h /run/miso/bootmnt/ | awk '{ print $1 }' | grep '/dev/')" | sed 's|/dev/||'g)"
-if [ "$(echo "$DEVICE_LIVE_BOOT_TMP" | grep dm)" != "" ];
-then
-    DEVICE_LIVE_BOOT="$(ls /sys/block/${DEVICE_LIVE_BOOT_TMP}/slaves | sed 's|[0-9]||g')"
+if [ "$(echo "$DEVICE_LIVE_BOOT_TMP" | grep dm)" != "" ]; then
+	DEVICE_LIVE_BOOT="$(ls /sys/block/${DEVICE_LIVE_BOOT_TMP}/slaves | sed 's|[0-9]||g')"
 else
-    DEVICE_LIVE_BOOT="$DEVICE_LIVE_BOOT_TMP"
+	DEVICE_LIVE_BOOT="$DEVICE_LIVE_BOOT_TMP"
 fi
 
-
-for i in $(LANGUAGE=C fdisk -l | grep -e "EFI System" -e "FAT" | cut -f1 -d" " | grep -v "$DEVICE_LIVE_BOOT")
-do
-    umount -l /boot/efi
-    mount "$i" /boot/efi
-    if [ -d /boot/efi/EFI ];
-    then
-        echo "$i" >> /tmp/efi-partitions
-    fi
-    umount -l /boot/efi
+for i in $(LANGUAGE=C fdisk -l | grep -e "EFI System" -e "FAT" | cut -f1 -d" " | grep -v "$DEVICE_LIVE_BOOT"); do
+	umount -l /boot/efi
+	mount "$i" /boot/efi
+	if [ -d /boot/efi/EFI ]; then
+		echo "$i" >>/tmp/efi-partitions
+	fi
+	umount -l /boot/efi
 
 done
 
 # Umount partitions
-for i in $(blkid | grep -v 'TYPE="swap"'| grep -v 'TYPE="squashfs"' | grep -v '^/dev/sr0' | cut -f1 -d":")
-do
-    umount "$i"
+for i in $(blkid | grep -v 'TYPE="swap"' | grep -v 'TYPE="squashfs"' | grep -v '^/dev/sr0' | cut -f1 -d":"); do
+	umount "$i"
 done
 
 # boot EFI without partition EFI
-if [ -d /sys/firmware/efi ] && [ "$(cat /tmp/efi-partitions)" = "" ] ;
-then
-LIVEBOOT=EFI
-PARTITION=LEGACY
+if [ -d /sys/firmware/efi ] && [ "$(cat /tmp/efi-partitions)" = "" ]; then
+	LIVEBOOT=EFI
+	PARTITION=LEGACY
 
-TEXT_01=$"Do you want to proceed with the installation in EFI mode?"
-TEXT_02=$"The current boot is using <span color='#CC2222'>EFI</span> mode, but I did not find any EFI partition on this computer.
+	TEXT_01=$"Do you want to proceed with the installation in EFI mode?"
+	TEXT_02=$"The current boot is using <span color='#CC2222'>EFI</span> mode, but I did not find any EFI partition on this computer.
 
 If this computer already has another system installed and you intend 
 to keep it installed, you will probably need to change the 
 configuration in the BIOS to boot in Legacy mode, also 
 called BIOS mode."
-yad --image=drive-harddisk --image-on-top --form --width=500 --height=100 --fixed \
---align=center \
---field="<b>$TEXT_01</b>
+	yad --image=drive-harddisk --image-on-top --form --width=500 --height=100 --fixed \
+		--align=center \
+		--field="<b>$TEXT_01</b>
 :LBL" \
---text "$TEXT_02
+		--text "$TEXT_02
 " \
---button=$"Continue"!gtk-apply:0 \
---button=$"Close"!gtk-cancel:1 \
---center --on-top --borders=20 --title=$"Install the system" \
---window-icon="/usr/share/icons/hicolor/scalable/apps/icon-big-hd-install.svg"
+		--button=$"Continue"!gtk-apply:0 \
+		--button=$"Close"!gtk-cancel:1 \
+		--center --on-top --borders=20 --title=$"Install the system" \
+		--window-icon="/usr/share/icons/hicolor/scalable/apps/icon-big-hd-install.svg"
 
-    if [ "$?" = "1" ]; then
-        exit
-    fi
+	if [ "$?" = "1" ]; then
+		exit
+	fi
 fi
-
 
 # legacy boot and EFI partition
 if [ ! -d /sys/firmware/efi ] && [ "$(cat /tmp/efi-partitions)" != "" ]; then
-LIVEBOOT=LEGACY
-PARTITION=EFI
-TEXT_03=$"Do you want to proceed with the installation in Legacy/BIOS mode?"
-TEXT_04=$"The current boot is using <span color='#CC2222'>Legacy/BIOS</span> mode, but I found at least one EFI partition on this computer. 
+	LIVEBOOT=LEGACY
+	PARTITION=EFI
+	TEXT_03=$"Do you want to proceed with the installation in Legacy/BIOS mode?"
+	TEXT_04=$"The current boot is using <span color='#CC2222'>Legacy/BIOS</span> mode, but I found at least one EFI partition on this computer. 
 
 For the installation to be successful, you will probably need to 
 change the configuration in the BIOS to boot in EFI or UEFI mode."
-yad --image=drive-harddisk --image-on-top --form --width=500 --height=100 --fixed \
---align=center \
---field="<b>$TEXT_03</b>
+	yad --image=drive-harddisk --image-on-top --form --width=500 --height=100 --fixed \
+		--align=center \
+		--field="<b>$TEXT_03</b>
 :LBL" \
---text "$TEXT_04
+		--text "$TEXT_04
 " \
---button=$"Continue"!gtk-apply:0 \
---button=$"Close"!gtk-cancel:1 \
---center --on-top --borders=20 --title=$"Install the system" \
---window-icon="/usr/share/icons/hicolor/scalable/apps/icon-big-hd-install.svg"
+		--button=$"Continue"!gtk-apply:0 \
+		--button=$"Close"!gtk-cancel:1 \
+		--center --on-top --borders=20 --title=$"Install the system" \
+		--window-icon="/usr/share/icons/hicolor/scalable/apps/icon-big-hd-install.svg"
 
-    if [ "$?" = "1" ]; then
-        exit
-    fi
+	if [ "$?" = "1" ]; then
+		exit
+	fi
 fi
 
 rm -f /tmp/start_calamares
@@ -373,39 +399,39 @@ bigbashview -s 1100x600 -n $"Install System" -p bbv-calamares -c transparent -w 
 
 # Start calamares
 if [ -e "/tmp/start_calamares" ]; then
-    cp -f /usr/share/biglinux/themes/biglinux/.config/kdeglobals /root/.config/kdeglobals
-    sudo QT_QUICK_BACKEND=software /usr/bin/calamares-manjaro
+	cp -f /usr/share/biglinux/themes/biglinux/.config/kdeglobals /root/.config/kdeglobals
+	sudo QT_QUICK_BACKEND=software /usr/bin/calamares-manjaro
 
-  #Calamares failed to install
-  if [ "$(grep -w completion /root/.cache/calamares/session.log | grep -v bash-completion | rev | cut -d ":" -f1 | rev | sed 's/^[ \t]*//;s/[ \t]*$//')" != "succeeded" ];then
-  # if [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "failed" ];then
-      user=$(ls /home)
-      cp /root/.cache/calamares/session.log /home/$user/calamares.log
-      chown $user:$user /home/$user/calamares.log
-      
-    send () {
-        sudo -u $user curl --data-binary -H "filename: /home/$user/calamares.log" https://filebin.net | tee "/home/$user/transfer.url" | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Sending, please wait..."
-        
-        if [ -f /usr/bin/falkon ]; then
-            sudo -u $user falkon https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
-        elif [ -f /usr/bin/brave ]; then
-            sudo -u $user brave-browser --new-window --no-sandbox https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
-        fi
-    }
+	#Calamares failed to install
+	if [ "$(grep -w completion /root/.cache/calamares/session.log | grep -v bash-completion | rev | cut -d ":" -f1 | rev | sed 's/^[ \t]*//;s/[ \t]*$//')" != "succeeded" ]; then
+		# if [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "failed" ];then
+		user=$(ls /home)
+		cp /root/.cache/calamares/session.log /home/$user/calamares.log
+		chown $user:$user /home/$user/calamares.log
 
-    yad --buttons-layout=center \
-        --width=480 \
-        --button=$"Open":1 \
-        --button=$"Send to the cloud":2 \
-        --button=$"Close":3 \
-        --title=$"calamares LOG" \
-        --text=$"\nDo you want to view or send the installation log file to the cloud?\nGenerate a link to send in support groups.\n"
+		send() {
+			sudo -u $user curl --data-binary -H "filename: /home/$user/calamares.log" https://filebin.net | tee "/home/$user/transfer.url" | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Sending, please wait..."
 
-    case $? in
-        1) sudo -u $user kate /home/$user/calamares.log ;;
-        2) send ;;
-        3) echo $"Closing file..." ;;
-    esac
+			if [ -f /usr/bin/falkon ]; then
+				sudo -u $user falkon https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
+			elif [ -f /usr/bin/brave ]; then
+				sudo -u $user brave-browser --new-window --no-sandbox https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
+			fi
+		}
 
-  fi
+		yad --buttons-layout=center \
+			--width=480 \
+			--button=$"Open":1 \
+			--button=$"Send to the cloud":2 \
+			--button=$"Close":3 \
+			--title=$"calamares LOG" \
+			--text=$"\nDo you want to view or send the installation log file to the cloud?\nGenerate a link to send in support groups.\n"
+
+		case $? in
+		1) sudo -u $user kate /home/$user/calamares.log ;;
+		2) send ;;
+		3) echo $"Closing file..." ;;
+		esac
+
+	fi
 fi
